#!/usr/bin/env bash
# This script displays all processes in a user-oriented format with process hierarchy.
ps -eo user,lstart,command --forest | awk 'NR==1 {print "USER STARTED COMMAND"} NR>1 {cmd=""; for(i=7;i<=NF;i++) {cmd = cmd $i " "} print $1, $5, cmd}'

