#!/usr/bin/env bash
# This is a script that displays the PID, along with the process name, of processes whose name contains the word bash, excluding itself.

pgrep -l "bash" | grep -v "$(basename $0)"
